/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operandos {
	double a;
	double b;
};
typedef struct operandos operandos;

#define Calculadora 0x31111111
#define Calculadora_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  double * suma_1(operandos *, CLIENT *);
extern  double * suma_1_svc(operandos *, struct svc_req *);
#define RESTA 2
extern  double * resta_1(operandos *, CLIENT *);
extern  double * resta_1_svc(operandos *, struct svc_req *);
#define MULTIPLICACION 3
extern  double * multiplicacion_1(operandos *, CLIENT *);
extern  double * multiplicacion_1_svc(operandos *, struct svc_req *);
#define DIVISION 4
extern  double * division_1(operandos *, CLIENT *);
extern  double * division_1_svc(operandos *, struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  double * suma_1();
extern  double * suma_1_svc();
#define RESTA 2
extern  double * resta_1();
extern  double * resta_1_svc();
#define MULTIPLICACION 3
extern  double * multiplicacion_1();
extern  double * multiplicacion_1_svc();
#define DIVISION 4
extern  double * division_1();
extern  double * division_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operandos (XDR *, operandos*);

#else /* K&R C */
extern bool_t xdr_operandos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
