/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void  //declaramos varibables a  y b de las operaciones
calculadora_1(char *host,double a,double b,int operacion)
{
	CLIENT *clnt;
	double  *result_1;
	operandos  suma_1_arg;
	double  *result_2;
	operandos  resta_1_arg;
	double  *result_3;
	operandos  multiplicacion_1_arg;
	double  *result_4;
	operandos  division_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, Calculadora, Calculadora_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch (operacion)
	{
	case 1:	

		suma_1_arg.a=a;
		suma_1_arg.b=b;
		result_1 = suma_1(&suma_1_arg, clnt);
			if (result_1 == (double *) NULL) {
				clnt_perror (clnt, "call failed");
			}else{
				printf("Resultado de la suma= %lf\n",*result_1);
			}
		break;

	case 2:

		resta_1_arg.a=a;
		resta_1_arg.b=b;
		result_2 = resta_1(&resta_1_arg, clnt);
			if (result_2 == (double *) NULL) {
				clnt_perror (clnt, "call failed");
			}else{
				printf("Resultado de la resta= %lf\n",*result_2);
			}
		break;

	case 3:

		multiplicacion_1_arg.a=a;
		multiplicacion_1_arg.b=b;
		result_3 = multiplicacion_1(&multiplicacion_1_arg, clnt);
			if (result_3 == (double *) NULL) {
				clnt_perror (clnt, "call failed");
			}else{
				printf("Resultado de la multiplicacion= %lf\n",*result_3);
			}
		break;

	case 4:

		division_1_arg.a=a;
		division_1_arg.b=b;
		result_4 = division_1(&division_1_arg, clnt);
			if (result_4 == (double *) NULL) {
				clnt_perror (clnt, "call failed");
			}else{
				printf("Resultado de la division= %lf\n",*result_4);
			}
		break;
	
	default:
		break;
	}

	

	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int operacion=0;
	if (argc < 2) {
		printf ("Uso: %s [servidor][Operando A][Operando B]\n", argv[0]);
		exit (1);
	}
	while(1){
		printf("Escoga la operacion a realizar:\n");
		printf("1.-Suma\n2.-Resta\n3.-Multiplicacion\n4.-Division\n--> ");
		scanf("%d",&operacion);
		if(operacion>0&&operacion<5){
			break;
		}else{
			printf("Operacion erronea, intente de nuevo\n\n");
			operacion=0;
		}
	}
	
	host = argv[1];
	//Enviamos valores ingresados por terminal
	calculadora_1 (host,atof(argv[2]),atof(argv[3]),operacion);
exit (0);
}
