/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

double *
suma_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static double  result;

	result=argp->a+argp->b;

	return &result;
}

double *
resta_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static double  result;

	result=argp->a-argp->b;

	return &result;
}

double *
multiplicacion_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static double  result;

	result=argp->a*argp->b;

	return &result;
}

double *
division_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static double  result;

	result=argp->a/argp->b;

	return &result;
}
